apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: currency-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: a3fcf67c65be44761ba731adaa50887e-3f1cab2a941cf08e.elb.ap-south-1.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: currency-service
            port:
              number: 80
